using System;

namespace System.Text.RegularExpressions
{
	/// <summary>The <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class is the base class for compiled regular expressions.</summary>
	// Token: 0x0200020C RID: 524
	public abstract class RegexRunner
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class.</summary>
		// Token: 0x06000F12 RID: 3858 RVA: 0x0000219B File Offset: 0x0000039B
		protected internal RegexRunner()
		{
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="regex">An instance of the regular expression engine.</param>
		/// <param name="text">The text to scan for a pattern match.</param>
		/// <param name="textbeg">The zero-based starting position in <paramref name="text" /> at which the regular expression engine scans for a match.</param>
		/// <param name="textend">The zero-based ending position in <paramref name="text" /> at which the regular expression engine scans for a match.</param>
		/// <param name="textstart">The zero-based starting position to scan for this match.</param>
		/// <param name="prevlen">The number of characters in the previous match.</param>
		/// <param name="quick">
		///   <see langword="true" /> to search for a match in quick mode; otherwise, <see langword="false" />.</param>
		/// <returns>A match.</returns>
		// Token: 0x06000F13 RID: 3859 RVA: 0x00043860 File Offset: 0x00041A60
		protected internal Match Scan(Regex regex, string text, int textbeg, int textend, int textstart, int prevlen, bool quick)
		{
			return this.Scan(regex, text, textbeg, textend, textstart, prevlen, quick, regex.MatchTimeout);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="regex">An instance of the regular expression engine.</param>
		/// <param name="text">The text to scan for a pattern match.</param>
		/// <param name="textbeg">The zero-based starting position in <paramref name="text" /> at which the regular expression engine scans for a match.</param>
		/// <param name="textend">The zero-based ending position in <paramref name="text" /> at which the regular expression engine scans for a match.</param>
		/// <param name="textstart">The zero-based starting position to scan for this match.</param>
		/// <param name="prevlen">The number of characters in the previous match.</param>
		/// <param name="quick">
		///   <see langword="true" /> to search for a match in quick mode; otherwise, <see langword="false" />.</param>
		/// <param name="timeout">The timeout interval.</param>
		/// <returns>A match.</returns>
		// Token: 0x06000F14 RID: 3860 RVA: 0x00043884 File Offset: 0x00041A84
		protected internal Match Scan(Regex regex, string text, int textbeg, int textend, int textstart, int prevlen, bool quick, TimeSpan timeout)
		{
			bool flag = false;
			Regex.ValidateMatchTimeout(timeout);
			this._ignoreTimeout = (Regex.InfiniteMatchTimeout == timeout);
			this._timeout = (this._ignoreTimeout ? ((int)Regex.InfiniteMatchTimeout.TotalMilliseconds) : ((int)(timeout.TotalMilliseconds + 0.5)));
			this.runregex = regex;
			this.runtext = text;
			this.runtextbeg = textbeg;
			this.runtextend = textend;
			this.runtextstart = textstart;
			int num = this.runregex.RightToLeft ? -1 : 1;
			int num2 = this.runregex.RightToLeft ? this.runtextbeg : this.runtextend;
			this.runtextpos = textstart;
			if (prevlen == 0)
			{
				if (this.runtextpos == num2)
				{
					return Match.Empty;
				}
				this.runtextpos += num;
			}
			this.StartTimeoutWatch();
			for (;;)
			{
				if (this.FindFirstChar())
				{
					this.CheckTimeout();
					if (!flag)
					{
						this.InitMatch();
						flag = true;
					}
					this.Go();
					if (this.runmatch._matchcount[0] > 0)
					{
						break;
					}
					this.runtrackpos = this.runtrack.Length;
					this.runstackpos = this.runstack.Length;
					this.runcrawlpos = this.runcrawl.Length;
				}
				if (this.runtextpos == num2)
				{
					goto Block_9;
				}
				this.runtextpos += num;
			}
			return this.TidyMatch(quick);
			Block_9:
			this.TidyMatch(true);
			return Match.Empty;
		}

		// Token: 0x06000F15 RID: 3861 RVA: 0x000439E6 File Offset: 0x00041BE6
		private void StartTimeoutWatch()
		{
			if (this._ignoreTimeout)
			{
				return;
			}
			this._timeoutChecksToSkip = 1000;
			this._timeoutOccursAt = Environment.TickCount + this._timeout;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F16 RID: 3862 RVA: 0x00043A0E File Offset: 0x00041C0E
		protected void CheckTimeout()
		{
			if (this._ignoreTimeout)
			{
				return;
			}
			this.DoCheckTimeout();
		}

		// Token: 0x06000F17 RID: 3863 RVA: 0x00043A20 File Offset: 0x00041C20
		private void DoCheckTimeout()
		{
			int num = this._timeoutChecksToSkip - 1;
			this._timeoutChecksToSkip = num;
			if (num != 0)
			{
				return;
			}
			this._timeoutChecksToSkip = 1000;
			int tickCount = Environment.TickCount;
			if (tickCount < this._timeoutOccursAt)
			{
				return;
			}
			if (0 > this._timeoutOccursAt && 0 < tickCount)
			{
				return;
			}
			throw new RegexMatchTimeoutException(this.runtext, this.runregex.pattern, TimeSpan.FromMilliseconds((double)this._timeout));
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F18 RID: 3864
		protected abstract void Go();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <returns>Returns <see cref="T:System.Boolean" />.</returns>
		// Token: 0x06000F19 RID: 3865
		protected abstract bool FindFirstChar();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F1A RID: 3866
		protected abstract void InitTrackCount();

		// Token: 0x06000F1B RID: 3867 RVA: 0x00043A8C File Offset: 0x00041C8C
		private void InitMatch()
		{
			if (this.runmatch == null)
			{
				if (this.runregex.caps != null)
				{
					this.runmatch = new MatchSparse(this.runregex, this.runregex.caps, this.runregex.capsize, this.runtext, this.runtextbeg, this.runtextend - this.runtextbeg, this.runtextstart);
				}
				else
				{
					this.runmatch = new Match(this.runregex, this.runregex.capsize, this.runtext, this.runtextbeg, this.runtextend - this.runtextbeg, this.runtextstart);
				}
			}
			else
			{
				this.runmatch.Reset(this.runregex, this.runtext, this.runtextbeg, this.runtextend, this.runtextstart);
			}
			if (this.runcrawl != null)
			{
				this.runtrackpos = this.runtrack.Length;
				this.runstackpos = this.runstack.Length;
				this.runcrawlpos = this.runcrawl.Length;
				return;
			}
			this.InitTrackCount();
			int num = this.runtrackcount * 8;
			int num2 = this.runtrackcount * 8;
			if (num < 32)
			{
				num = 32;
			}
			if (num2 < 16)
			{
				num2 = 16;
			}
			this.runtrack = new int[num];
			this.runtrackpos = num;
			this.runstack = new int[num2];
			this.runstackpos = num2;
			this.runcrawl = new int[32];
			this.runcrawlpos = 32;
		}

		// Token: 0x06000F1C RID: 3868 RVA: 0x00043BF5 File Offset: 0x00041DF5
		private Match TidyMatch(bool quick)
		{
			if (!quick)
			{
				Match match = this.runmatch;
				this.runmatch = null;
				match.Tidy(this.runtextpos);
				return match;
			}
			return null;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F1D RID: 3869 RVA: 0x00043C15 File Offset: 0x00041E15
		protected void EnsureStorage()
		{
			if (this.runstackpos < this.runtrackcount * 4)
			{
				this.DoubleStack();
			}
			if (this.runtrackpos < this.runtrackcount * 4)
			{
				this.DoubleTrack();
			}
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="index">The possible boundary position.</param>
		/// <param name="startpos">The starting position.</param>
		/// <param name="endpos">The ending position.</param>
		/// <returns>Returns <see cref="T:System.Boolean" />.</returns>
		// Token: 0x06000F1E RID: 3870 RVA: 0x00043C43 File Offset: 0x00041E43
		protected bool IsBoundary(int index, int startpos, int endpos)
		{
			return (index > startpos && RegexCharClass.IsWordChar(this.runtext[index - 1])) != (index < endpos && RegexCharClass.IsWordChar(this.runtext[index]));
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="index">The possible ECMA boundary position.</param>
		/// <param name="startpos">The starting position.</param>
		/// <param name="endpos">The ending position.</param>
		/// <returns>Returns <see cref="T:System.Boolean" />.</returns>
		// Token: 0x06000F1F RID: 3871 RVA: 0x00043C7C File Offset: 0x00041E7C
		protected bool IsECMABoundary(int index, int startpos, int endpos)
		{
			return (index > startpos && RegexCharClass.IsECMAWordChar(this.runtext[index - 1])) != (index < endpos && RegexCharClass.IsECMAWordChar(this.runtext[index]));
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="ch">A character.</param>
		/// <param name="set">The character set.</param>
		/// <param name="category">The character category.</param>
		/// <returns>Returns <see cref="T:System.Boolean" />.</returns>
		// Token: 0x06000F20 RID: 3872 RVA: 0x00043CB8 File Offset: 0x00041EB8
		protected static bool CharInSet(char ch, string set, string category)
		{
			string set2 = RegexCharClass.ConvertOldStringsToClass(set, category);
			return RegexCharClass.CharInClass(ch, set2);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. Determines whether a character is in a character class.</summary>
		/// <param name="ch">A character to test.</param>
		/// <param name="charClass">The internal name of a character class.</param>
		/// <returns>
		///   <see langword="true" /> if the <paramref name="ch" /> parameter is in the character class specified by the <paramref name="charClass" /> parameter.</returns>
		// Token: 0x06000F21 RID: 3873 RVA: 0x00043CD4 File Offset: 0x00041ED4
		protected static bool CharInClass(char ch, string charClass)
		{
			return RegexCharClass.CharInClass(ch, charClass);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F22 RID: 3874 RVA: 0x00043CE0 File Offset: 0x00041EE0
		protected void DoubleTrack()
		{
			int[] destinationArray = new int[this.runtrack.Length * 2];
			Array.Copy(this.runtrack, 0, destinationArray, this.runtrack.Length, this.runtrack.Length);
			this.runtrackpos += this.runtrack.Length;
			this.runtrack = destinationArray;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F23 RID: 3875 RVA: 0x00043D38 File Offset: 0x00041F38
		protected void DoubleStack()
		{
			int[] destinationArray = new int[this.runstack.Length * 2];
			Array.Copy(this.runstack, 0, destinationArray, this.runstack.Length, this.runstack.Length);
			this.runstackpos += this.runstack.Length;
			this.runstack = destinationArray;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F24 RID: 3876 RVA: 0x00043D90 File Offset: 0x00041F90
		protected void DoubleCrawl()
		{
			int[] destinationArray = new int[this.runcrawl.Length * 2];
			Array.Copy(this.runcrawl, 0, destinationArray, this.runcrawl.Length, this.runcrawl.Length);
			this.runcrawlpos += this.runcrawl.Length;
			this.runcrawl = destinationArray;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="i">A number to save.</param>
		// Token: 0x06000F25 RID: 3877 RVA: 0x00043DE8 File Offset: 0x00041FE8
		protected void Crawl(int i)
		{
			if (this.runcrawlpos == 0)
			{
				this.DoubleCrawl();
			}
			int[] array = this.runcrawl;
			int num = this.runcrawlpos - 1;
			this.runcrawlpos = num;
			array[num] = i;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <returns>Returns <see cref="T:System.Int32" />.</returns>
		// Token: 0x06000F26 RID: 3878 RVA: 0x00043E1C File Offset: 0x0004201C
		protected int Popcrawl()
		{
			int[] array = this.runcrawl;
			int num = this.runcrawlpos;
			this.runcrawlpos = num + 1;
			return array[num];
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <returns>Returns <see cref="T:System.Int32" />.</returns>
		// Token: 0x06000F27 RID: 3879 RVA: 0x00043E41 File Offset: 0x00042041
		protected int Crawlpos()
		{
			return this.runcrawl.Length - this.runcrawlpos;
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="capnum">A capture number.</param>
		/// <param name="start">The starting position of the capture.</param>
		/// <param name="end">The ending position of the capture.</param>
		// Token: 0x06000F28 RID: 3880 RVA: 0x00043E52 File Offset: 0x00042052
		protected void Capture(int capnum, int start, int end)
		{
			if (end < start)
			{
				int num = end;
				end = start;
				start = num;
			}
			this.Crawl(capnum);
			this.runmatch.AddMatch(capnum, start, end - start);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="capnum">A capture number.</param>
		/// <param name="uncapnum">A saved capture number.</param>
		/// <param name="start">The starting position.</param>
		/// <param name="end">The ending position.</param>
		// Token: 0x06000F29 RID: 3881 RVA: 0x00043E78 File Offset: 0x00042078
		protected void TransferCapture(int capnum, int uncapnum, int start, int end)
		{
			if (end < start)
			{
				int num = end;
				end = start;
				start = num;
			}
			int num2 = this.MatchIndex(uncapnum);
			int num3 = num2 + this.MatchLength(uncapnum);
			if (start >= num3)
			{
				end = start;
				start = num3;
			}
			else if (end <= num2)
			{
				start = num2;
			}
			else
			{
				if (end > num3)
				{
					end = num3;
				}
				if (num2 > start)
				{
					start = num2;
				}
			}
			this.Crawl(uncapnum);
			this.runmatch.BalanceMatch(uncapnum);
			if (capnum != -1)
			{
				this.Crawl(capnum);
				this.runmatch.AddMatch(capnum, start, end - start);
			}
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x06000F2A RID: 3882 RVA: 0x00043EF8 File Offset: 0x000420F8
		protected void Uncapture()
		{
			int cap = this.Popcrawl();
			this.runmatch.RemoveMatch(cap);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="cap">The capture number.</param>
		/// <returns>Returns <see cref="T:System.Boolean" />.</returns>
		// Token: 0x06000F2B RID: 3883 RVA: 0x00043F18 File Offset: 0x00042118
		protected bool IsMatched(int cap)
		{
			return this.runmatch.IsMatched(cap);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="cap">The capture number.</param>
		/// <returns>Returns <see cref="T:System.Int32" />.</returns>
		// Token: 0x06000F2C RID: 3884 RVA: 0x00043F26 File Offset: 0x00042126
		protected int MatchIndex(int cap)
		{
			return this.runmatch.MatchIndex(cap);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		/// <param name="cap">The capture number.</param>
		/// <returns>Returns <see cref="T:System.Int32" />.</returns>
		// Token: 0x06000F2D RID: 3885 RVA: 0x00043F34 File Offset: 0x00042134
		protected int MatchLength(int cap)
		{
			return this.runmatch.MatchLength(cap);
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000968 RID: 2408
		protected internal int runtextbeg;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000969 RID: 2409
		protected internal int runtextend;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x0400096A RID: 2410
		protected internal int runtextstart;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x0400096B RID: 2411
		protected internal string runtext;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x0400096C RID: 2412
		protected internal int runtextpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x0400096D RID: 2413
		protected internal int[] runtrack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x0400096E RID: 2414
		protected internal int runtrackpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x0400096F RID: 2415
		protected internal int[] runstack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000970 RID: 2416
		protected internal int runstackpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000971 RID: 2417
		protected internal int[] runcrawl;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000972 RID: 2418
		protected internal int runcrawlpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000973 RID: 2419
		protected internal int runtrackcount;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000974 RID: 2420
		protected internal Match runmatch;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x04000975 RID: 2421
		protected internal Regex runregex;

		// Token: 0x04000976 RID: 2422
		private int _timeout;

		// Token: 0x04000977 RID: 2423
		private bool _ignoreTimeout;

		// Token: 0x04000978 RID: 2424
		private int _timeoutOccursAt;

		// Token: 0x04000979 RID: 2425
		private const int TimeoutCheckFrequency = 1000;

		// Token: 0x0400097A RID: 2426
		private int _timeoutChecksToSkip;
	}
}
