using System;
using System.Collections;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;
using Unity;

namespace System.Data
{
	/// <summary>Represents a collection of constraints for a <see cref="T:System.Data.DataTable" />.</summary>
	// Token: 0x020000AA RID: 170
	[DefaultEvent("CollectionChanged")]
	public sealed class ConstraintCollection : InternalDataCollectionBase
	{
		// Token: 0x06000A70 RID: 2672 RVA: 0x0002B86B File Offset: 0x00029A6B
		internal ConstraintCollection(DataTable table)
		{
			this._list = new ArrayList();
			this._defaultNameIndex = 1;
			base..ctor();
			this._table = table;
		}

		// Token: 0x170001BD RID: 445
		// (get) Token: 0x06000A71 RID: 2673 RVA: 0x0002B88C File Offset: 0x00029A8C
		protected override ArrayList List
		{
			get
			{
				return this._list;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Constraint" /> from the collection at the specified index.</summary>
		/// <param name="index">The index of the constraint to return.</param>
		/// <returns>The <see cref="T:System.Data.Constraint" /> at the specified index.</returns>
		/// <exception cref="T:System.IndexOutOfRangeException">The index value is greater than the number of items in the collection.</exception>
		// Token: 0x170001BE RID: 446
		public Constraint this[int index]
		{
			get
			{
				if (index >= 0 && index < this.List.Count)
				{
					return (Constraint)this.List[index];
				}
				throw ExceptionBuilder.ConstraintOutOfRange(index);
			}
		}

		// Token: 0x170001BF RID: 447
		// (get) Token: 0x06000A73 RID: 2675 RVA: 0x0002B8C0 File Offset: 0x00029AC0
		internal DataTable Table
		{
			get
			{
				return this._table;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Constraint" /> from the collection with the specified name.</summary>
		/// <param name="name">The <see cref="P:System.Data.Constraint.ConstraintName" /> of the constraint to return.</param>
		/// <returns>The <see cref="T:System.Data.Constraint" /> with the specified name; otherwise a null value if the <see cref="T:System.Data.Constraint" /> does not exist.</returns>
		// Token: 0x170001C0 RID: 448
		public Constraint this[string name]
		{
			get
			{
				int num = this.InternalIndexOf(name);
				if (num == -2)
				{
					throw ExceptionBuilder.CaseInsensitiveNameConflict(name);
				}
				if (num >= 0)
				{
					return (Constraint)this.List[num];
				}
				return null;
			}
		}

		/// <summary>Adds the specified <see cref="T:System.Data.Constraint" /> object to the collection.</summary>
		/// <param name="constraint">The <see langword="Constraint" /> to add.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="constraint" /> argument is null.</exception>
		/// <exception cref="T:System.ArgumentException">The constraint already belongs to this collection, or belongs to another collection.</exception>
		/// <exception cref="T:System.Data.DuplicateNameException">The collection already has a constraint with the same name. (The comparison is not case-sensitive.)</exception>
		// Token: 0x06000A75 RID: 2677 RVA: 0x0002B900 File Offset: 0x00029B00
		public void Add(Constraint constraint)
		{
			this.Add(constraint, true);
		}

		// Token: 0x06000A76 RID: 2678 RVA: 0x0002B90C File Offset: 0x00029B0C
		internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (this.FindConstraint(constraint) != null)
			{
				throw ExceptionBuilder.DuplicateConstraint(this.FindConstraint(constraint).ConstraintName);
			}
			if (1 < this._table.NestedParentRelations.Length && !this.AutoGenerated(constraint))
			{
				throw ExceptionBuilder.CantAddConstraintToMultipleNestedTable(this._table.TableName);
			}
			if (constraint is UniqueConstraint)
			{
				if (((UniqueConstraint)constraint)._bPrimaryKey && this.Table._primaryKey != null)
				{
					throw ExceptionBuilder.AddPrimaryKeyConstraint();
				}
				this.AddUniqueConstraint((UniqueConstraint)constraint);
			}
			else if (constraint is ForeignKeyConstraint)
			{
				ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)constraint;
				if (addUniqueWhenAddingForeign && foreignKeyConstraint.RelatedTable.Constraints.FindKeyConstraint(foreignKeyConstraint.RelatedColumnsReference) == null)
				{
					if (constraint.ConstraintName.Length == 0)
					{
						constraint.ConstraintName = this.AssignName();
					}
					else
					{
						this.RegisterName(constraint.ConstraintName);
					}
					UniqueConstraint constraint2 = new UniqueConstraint(foreignKeyConstraint.RelatedColumnsReference);
					foreignKeyConstraint.RelatedTable.Constraints.Add(constraint2);
				}
				this.AddForeignKeyConstraint((ForeignKeyConstraint)constraint);
			}
			this.BaseAdd(constraint);
			this.ArrayAdd(constraint);
			this.OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, constraint));
			if (constraint is UniqueConstraint && ((UniqueConstraint)constraint)._bPrimaryKey)
			{
				this.Table.PrimaryKey = ((UniqueConstraint)constraint).ColumnsReference;
			}
		}

		/// <summary>Constructs a new <see cref="T:System.Data.UniqueConstraint" /> with the specified name, array of <see cref="T:System.Data.DataColumn" /> objects, and value that indicates whether the column is a primary key, and adds it to the collection.</summary>
		/// <param name="name">The name of the <see cref="T:System.Data.UniqueConstraint" />.</param>
		/// <param name="columns">An array of <see cref="T:System.Data.DataColumn" /> objects to which the constraint applies.</param>
		/// <param name="primaryKey">Specifies whether the column should be the primary key. If <see langword="true" />, the column will be a primary key column.</param>
		/// <returns>A new <see langword="UniqueConstraint" />.</returns>
		/// <exception cref="T:System.ArgumentException">The constraint already belongs to this collection.  
		///  -Or-  
		///  The constraint belongs to another collection.</exception>
		/// <exception cref="T:System.Data.DuplicateNameException">The collection already has a constraint with the specified name. (The comparison is not case-sensitive.)</exception>
		// Token: 0x06000A77 RID: 2679 RVA: 0x0002BA64 File Offset: 0x00029C64
		public Constraint Add(string name, DataColumn[] columns, bool primaryKey)
		{
			UniqueConstraint uniqueConstraint = new UniqueConstraint(name, columns);
			this.Add(uniqueConstraint);
			if (primaryKey)
			{
				this.Table.PrimaryKey = columns;
			}
			return uniqueConstraint;
		}

		/// <summary>Constructs a new <see cref="T:System.Data.UniqueConstraint" /> with the specified name, <see cref="T:System.Data.DataColumn" />, and value that indicates whether the column is a primary key, and adds it to the collection.</summary>
		/// <param name="name">The name of the <see langword="UniqueConstraint" />.</param>
		/// <param name="column">The <see cref="T:System.Data.DataColumn" /> to which the constraint applies.</param>
		/// <param name="primaryKey">Specifies whether the column should be the primary key. If <see langword="true" />, the column will be a primary key column.</param>
		/// <returns>A new <see langword="UniqueConstraint" />.</returns>
		/// <exception cref="T:System.ArgumentException">The constraint already belongs to this collection.  
		///  -Or-  
		///  The constraint belongs to another collection.</exception>
		/// <exception cref="T:System.Data.DuplicateNameException">The collection already has a constraint with the specified name. (The comparison is not case-sensitive.)</exception>
		// Token: 0x06000A78 RID: 2680 RVA: 0x0002BA90 File Offset: 0x00029C90
		public Constraint Add(string name, DataColumn column, bool primaryKey)
		{
			UniqueConstraint uniqueConstraint = new UniqueConstraint(name, column);
			this.Add(uniqueConstraint);
			if (primaryKey)
			{
				this.Table.PrimaryKey = uniqueConstraint.ColumnsReference;
			}
			return uniqueConstraint;
		}

		/// <summary>Constructs a new <see cref="T:System.Data.ForeignKeyConstraint" /> with the specified name, parent column, and child column, and adds the constraint to the collection.</summary>
		/// <param name="name">The name of the <see cref="T:System.Data.ForeignKeyConstraint" />.</param>
		/// <param name="primaryKeyColumn">The primary key, or parent, <see cref="T:System.Data.DataColumn" />.</param>
		/// <param name="foreignKeyColumn">The foreign key, or child, <see cref="T:System.Data.DataColumn" />.</param>
		/// <returns>A new <see langword="ForeignKeyConstraint" />.</returns>
		// Token: 0x06000A79 RID: 2681 RVA: 0x0002BAC4 File Offset: 0x00029CC4
		public Constraint Add(string name, DataColumn primaryKeyColumn, DataColumn foreignKeyColumn)
		{
			ForeignKeyConstraint foreignKeyConstraint = new ForeignKeyConstraint(name, primaryKeyColumn, foreignKeyColumn);
			this.Add(foreignKeyConstraint);
			return foreignKeyConstraint;
		}

		/// <summary>Constructs a new <see cref="T:System.Data.ForeignKeyConstraint" />, with the specified arrays of parent columns and child columns, and adds the constraint to the collection.</summary>
		/// <param name="name">The name of the <see cref="T:System.Data.ForeignKeyConstraint" />.</param>
		/// <param name="primaryKeyColumns">An array of <see cref="T:System.Data.DataColumn" /> objects that are the primary key, or parent, columns.</param>
		/// <param name="foreignKeyColumns">An array of <see cref="T:System.Data.DataColumn" /> objects that are the foreign key, or child, columns.</param>
		/// <returns>A new <see langword="ForeignKeyConstraint" />.</returns>
		// Token: 0x06000A7A RID: 2682 RVA: 0x0002BAE4 File Offset: 0x00029CE4
		public Constraint Add(string name, DataColumn[] primaryKeyColumns, DataColumn[] foreignKeyColumns)
		{
			ForeignKeyConstraint foreignKeyConstraint = new ForeignKeyConstraint(name, primaryKeyColumns, foreignKeyColumns);
			this.Add(foreignKeyConstraint);
			return foreignKeyConstraint;
		}

		/// <summary>Copies the elements of the specified <see cref="T:System.Data.ConstraintCollection" /> array to the end of the collection.</summary>
		/// <param name="constraints">An array of <see cref="T:System.Data.ConstraintCollection" /> objects to add to the collection.</param>
		// Token: 0x06000A7B RID: 2683 RVA: 0x0002BB04 File Offset: 0x00029D04
		public void AddRange(Constraint[] constraints)
		{
			if (this._table.fInitInProgress)
			{
				this._delayLoadingConstraints = constraints;
				this._fLoadForeignKeyConstraintsOnly = false;
				return;
			}
			if (constraints != null)
			{
				foreach (Constraint constraint in constraints)
				{
					if (constraint != null)
					{
						this.Add(constraint);
					}
				}
			}
		}

		// Token: 0x06000A7C RID: 2684 RVA: 0x0002BB50 File Offset: 0x00029D50
		private void AddUniqueConstraint(UniqueConstraint constraint)
		{
			DataColumn[] columnsReference = constraint.ColumnsReference;
			for (int i = 0; i < columnsReference.Length; i++)
			{
				if (columnsReference[i].Table != this._table)
				{
					throw ExceptionBuilder.ConstraintForeignTable();
				}
			}
			constraint.ConstraintIndexInitialize();
			if (!constraint.CanEnableConstraint())
			{
				constraint.ConstraintIndexClear();
				throw ExceptionBuilder.UniqueConstraintViolation();
			}
		}

		// Token: 0x06000A7D RID: 2685 RVA: 0x0002BBA2 File Offset: 0x00029DA2
		private void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
		{
			if (!constraint.CanEnableConstraint())
			{
				throw ExceptionBuilder.ConstraintParentValues();
			}
			constraint.CheckCanAddToCollection(this);
		}

		// Token: 0x06000A7E RID: 2686 RVA: 0x0002BBBC File Offset: 0x00029DBC
		private bool AutoGenerated(Constraint constraint)
		{
			ForeignKeyConstraint foreignKeyConstraint = constraint as ForeignKeyConstraint;
			if (foreignKeyConstraint != null)
			{
				return XmlTreeGen.AutoGenerated(foreignKeyConstraint, false);
			}
			return XmlTreeGen.AutoGenerated((UniqueConstraint)constraint);
		}

		/// <summary>Occurs whenever the <see cref="T:System.Data.ConstraintCollection" /> is changed because of <see cref="T:System.Data.Constraint" /> objects being added or removed.</summary>
		// Token: 0x14000012 RID: 18
		// (add) Token: 0x06000A7F RID: 2687 RVA: 0x0002BBE6 File Offset: 0x00029DE6
		// (remove) Token: 0x06000A80 RID: 2688 RVA: 0x0002BBFF File Offset: 0x00029DFF
		public event CollectionChangeEventHandler CollectionChanged
		{
			add
			{
				this._onCollectionChanged = (CollectionChangeEventHandler)Delegate.Combine(this._onCollectionChanged, value);
			}
			remove
			{
				this._onCollectionChanged = (CollectionChangeEventHandler)Delegate.Remove(this._onCollectionChanged, value);
			}
		}

		// Token: 0x06000A81 RID: 2689 RVA: 0x0002BC18 File Offset: 0x00029E18
		private void ArrayAdd(Constraint constraint)
		{
			this.List.Add(constraint);
		}

		// Token: 0x06000A82 RID: 2690 RVA: 0x0002BC27 File Offset: 0x00029E27
		private void ArrayRemove(Constraint constraint)
		{
			this.List.Remove(constraint);
		}

		// Token: 0x06000A83 RID: 2691 RVA: 0x0002BC35 File Offset: 0x00029E35
		internal string AssignName()
		{
			string result = this.MakeName(this._defaultNameIndex);
			this._defaultNameIndex++;
			return result;
		}

		// Token: 0x06000A84 RID: 2692 RVA: 0x0002BC51 File Offset: 0x00029E51
		private void BaseAdd(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (constraint.ConstraintName.Length == 0)
			{
				constraint.ConstraintName = this.AssignName();
			}
			else
			{
				this.RegisterName(constraint.ConstraintName);
			}
			constraint.InCollection = true;
		}

		// Token: 0x06000A85 RID: 2693 RVA: 0x0002BC90 File Offset: 0x00029E90
		private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength)
		{
			int num = 0;
			for (int i = 0; i < oldLength; i++)
			{
				bool flag = false;
				for (int j = num; j < newLength; j++)
				{
					if (oldArray[i] == newArray[j])
					{
						if (num == j)
						{
							num++;
						}
						flag = true;
						break;
					}
				}
				if (!flag)
				{
					this.BaseRemove(oldArray[i]);
					this.List.Remove(oldArray[i]);
				}
			}
			for (int k = 0; k < newLength; k++)
			{
				if (!newArray[k].InCollection)
				{
					this.BaseAdd(newArray[k]);
				}
				this.List.Add(newArray[k]);
			}
		}

		// Token: 0x06000A86 RID: 2694 RVA: 0x0002BD20 File Offset: 0x00029F20
		private void BaseRemove(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (constraint.Table != this._table)
			{
				throw ExceptionBuilder.ConstraintRemoveFailed();
			}
			this.UnregisterName(constraint.ConstraintName);
			constraint.InCollection = false;
			if (constraint is UniqueConstraint)
			{
				for (int i = 0; i < this.Table.ChildRelations.Count; i++)
				{
					DataRelation dataRelation = this.Table.ChildRelations[i];
					if (dataRelation.ParentKeyConstraint == constraint)
					{
						dataRelation.SetParentKeyConstraint(null);
					}
				}
				((UniqueConstraint)constraint).ConstraintIndexClear();
				return;
			}
			if (constraint is ForeignKeyConstraint)
			{
				for (int j = 0; j < this.Table.ParentRelations.Count; j++)
				{
					DataRelation dataRelation2 = this.Table.ParentRelations[j];
					if (dataRelation2.ChildKeyConstraint == constraint)
					{
						dataRelation2.SetChildKeyConstraint(null);
					}
				}
			}
		}

		/// <summary>Indicates whether a <see cref="T:System.Data.Constraint" /> can be removed.</summary>
		/// <param name="constraint">The <see cref="T:System.Data.Constraint" /> to be tested for removal from the collection.</param>
		/// <returns>
		///   <see langword="true" /> if the <see cref="T:System.Data.Constraint" /> can be removed from collection; otherwise, <see langword="false" />.</returns>
		// Token: 0x06000A87 RID: 2695 RVA: 0x0002BDF8 File Offset: 0x00029FF8
		public bool CanRemove(Constraint constraint)
		{
			return this.CanRemove(constraint, false);
		}

		// Token: 0x06000A88 RID: 2696 RVA: 0x0002BE02 File Offset: 0x0002A002
		internal bool CanRemove(Constraint constraint, bool fThrowException)
		{
			return constraint.CanBeRemovedFromCollection(this, fThrowException);
		}

		/// <summary>Clears the collection of any <see cref="T:System.Data.Constraint" /> objects.</summary>
		// Token: 0x06000A89 RID: 2697 RVA: 0x0002BE0C File Offset: 0x0002A00C
		public void Clear()
		{
			if (this._table != null)
			{
				this._table.PrimaryKey = null;
				for (int i = 0; i < this._table.ParentRelations.Count; i++)
				{
					this._table.ParentRelations[i].SetChildKeyConstraint(null);
				}
				for (int j = 0; j < this._table.ChildRelations.Count; j++)
				{
					this._table.ChildRelations[j].SetParentKeyConstraint(null);
				}
			}
			if (this._table.fInitInProgress && this._delayLoadingConstraints != null)
			{
				this._delayLoadingConstraints = null;
				this._fLoadForeignKeyConstraintsOnly = false;
			}
			int count = this.List.Count;
			Constraint[] array = new Constraint[this.List.Count];
			this.List.CopyTo(array, 0);
			try
			{
				this.BaseGroupSwitch(array, count, null, 0);
			}
			catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
			{
				this.BaseGroupSwitch(null, 0, array, count);
				this.List.Clear();
				for (int k = 0; k < count; k++)
				{
					this.List.Add(array[k]);
				}
				throw;
			}
			this.List.Clear();
			this.OnCollectionChanged(InternalDataCollectionBase.s_refreshEventArgs);
		}

		/// <summary>Indicates whether the <see cref="T:System.Data.Constraint" /> object specified by name exists in the collection.</summary>
		/// <param name="name">The <see cref="P:System.Data.Constraint.ConstraintName" /> of the constraint.</param>
		/// <returns>
		///   <see langword="true" /> if the collection contains the specified constraint; otherwise, <see langword="false" />.</returns>
		// Token: 0x06000A8A RID: 2698 RVA: 0x0002BF60 File Offset: 0x0002A160
		public bool Contains(string name)
		{
			return this.InternalIndexOf(name) >= 0;
		}

		// Token: 0x06000A8B RID: 2699 RVA: 0x0002BF70 File Offset: 0x0002A170
		internal bool Contains(string name, bool caseSensitive)
		{
			if (!caseSensitive)
			{
				return this.Contains(name);
			}
			int num = this.InternalIndexOf(name);
			return num >= 0 && name == ((Constraint)this.List[num]).ConstraintName;
		}

		/// <summary>Copies the collection objects to a one-dimensional <see cref="T:System.Array" /> instance starting at the specified index.</summary>
		/// <param name="array">The one-dimensional <see cref="T:System.Array" /> that is the destination of the values copied from the collection.</param>
		/// <param name="index">The index of the array at which to start inserting.</param>
		// Token: 0x06000A8C RID: 2700 RVA: 0x0002BFB4 File Offset: 0x0002A1B4
		public void CopyTo(Constraint[] array, int index)
		{
			if (array == null)
			{
				throw ExceptionBuilder.ArgumentNull("array");
			}
			if (index < 0)
			{
				throw ExceptionBuilder.ArgumentOutOfRange("index");
			}
			if (array.Length - index < this._list.Count)
			{
				throw ExceptionBuilder.InvalidOffsetLength();
			}
			for (int i = 0; i < this._list.Count; i++)
			{
				array[index + i] = (Constraint)this._list[i];
			}
		}

		// Token: 0x06000A8D RID: 2701 RVA: 0x0002C024 File Offset: 0x0002A224
		internal Constraint FindConstraint(Constraint constraint)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				if (((Constraint)this.List[i]).Equals(constraint))
				{
					return (Constraint)this.List[i];
				}
			}
			return null;
		}

		// Token: 0x06000A8E RID: 2702 RVA: 0x0002C078 File Offset: 0x0002A278
		internal UniqueConstraint FindKeyConstraint(DataColumn[] columns)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				UniqueConstraint uniqueConstraint = this.List[i] as UniqueConstraint;
				if (uniqueConstraint != null && ConstraintCollection.CompareArrays(uniqueConstraint.Key.ColumnsReference, columns))
				{
					return uniqueConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000A8F RID: 2703 RVA: 0x0002C0CC File Offset: 0x0002A2CC
		internal UniqueConstraint FindKeyConstraint(DataColumn column)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				UniqueConstraint uniqueConstraint = this.List[i] as UniqueConstraint;
				if (uniqueConstraint != null && uniqueConstraint.Key.ColumnsReference.Length == 1 && uniqueConstraint.Key.ColumnsReference[0] == column)
				{
					return uniqueConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000A90 RID: 2704 RVA: 0x0002C130 File Offset: 0x0002A330
		internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				ForeignKeyConstraint foreignKeyConstraint = this.List[i] as ForeignKeyConstraint;
				if (foreignKeyConstraint != null && ConstraintCollection.CompareArrays(foreignKeyConstraint.ParentKey.ColumnsReference, parentColumns) && ConstraintCollection.CompareArrays(foreignKeyConstraint.ChildKey.ColumnsReference, childColumns))
				{
					return foreignKeyConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000A91 RID: 2705 RVA: 0x0002C19C File Offset: 0x0002A39C
		private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2)
		{
			if (a1.Length != a2.Length)
			{
				return false;
			}
			for (int i = 0; i < a1.Length; i++)
			{
				bool flag = false;
				for (int j = 0; j < a2.Length; j++)
				{
					if (a1[i] == a2[j])
					{
						flag = true;
						break;
					}
				}
				if (!flag)
				{
					return false;
				}
			}
			return true;
		}

		/// <summary>Gets the index of the specified <see cref="T:System.Data.Constraint" />.</summary>
		/// <param name="constraint">The <see cref="T:System.Data.Constraint" /> to search for.</param>
		/// <returns>The zero-based index of the <see cref="T:System.Data.Constraint" /> if it is in the collection; otherwise, -1.</returns>
		// Token: 0x06000A92 RID: 2706 RVA: 0x0002C1E4 File Offset: 0x0002A3E4
		public int IndexOf(Constraint constraint)
		{
			if (constraint != null)
			{
				int count = this.Count;
				for (int i = 0; i < count; i++)
				{
					if (constraint == (Constraint)this.List[i])
					{
						return i;
					}
				}
			}
			return -1;
		}

		/// <summary>Gets the index of the <see cref="T:System.Data.Constraint" /> specified by name.</summary>
		/// <param name="constraintName">The name of the <see cref="T:System.Data.Constraint" />.</param>
		/// <returns>The index of the <see cref="T:System.Data.Constraint" /> if it is in the collection; otherwise, -1.</returns>
		// Token: 0x06000A93 RID: 2707 RVA: 0x0002C220 File Offset: 0x0002A420
		public int IndexOf(string constraintName)
		{
			int num = this.InternalIndexOf(constraintName);
			if (num >= 0)
			{
				return num;
			}
			return -1;
		}

		// Token: 0x06000A94 RID: 2708 RVA: 0x0002C23C File Offset: 0x0002A43C
		internal int InternalIndexOf(string constraintName)
		{
			int num = -1;
			if (constraintName != null && 0 < constraintName.Length)
			{
				int count = this.List.Count;
				for (int i = 0; i < count; i++)
				{
					Constraint constraint = (Constraint)this.List[i];
					int num2 = base.NamesEqual(constraint.ConstraintName, constraintName, false, this._table.Locale);
					if (num2 == 1)
					{
						return i;
					}
					if (num2 == -1)
					{
						num = ((num == -1) ? i : -2);
					}
				}
			}
			return num;
		}

		// Token: 0x06000A95 RID: 2709 RVA: 0x0002C2B4 File Offset: 0x0002A4B4
		private string MakeName(int index)
		{
			if (1 == index)
			{
				return "Constraint1";
			}
			return "Constraint" + index.ToString(CultureInfo.InvariantCulture);
		}

		// Token: 0x06000A96 RID: 2710 RVA: 0x0002C2D6 File Offset: 0x0002A4D6
		private void OnCollectionChanged(CollectionChangeEventArgs ccevent)
		{
			CollectionChangeEventHandler onCollectionChanged = this._onCollectionChanged;
			if (onCollectionChanged == null)
			{
				return;
			}
			onCollectionChanged(this, ccevent);
		}

		// Token: 0x06000A97 RID: 2711 RVA: 0x0002C2EC File Offset: 0x0002A4EC
		internal void RegisterName(string name)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				if (base.NamesEqual(name, ((Constraint)this.List[i]).ConstraintName, true, this._table.Locale) != 0)
				{
					throw ExceptionBuilder.DuplicateConstraintName(((Constraint)this.List[i]).ConstraintName);
				}
			}
			if (base.NamesEqual(name, this.MakeName(this._defaultNameIndex), true, this._table.Locale) != 0)
			{
				this._defaultNameIndex++;
			}
		}

		/// <summary>Removes the specified <see cref="T:System.Data.Constraint" /> from the collection.</summary>
		/// <param name="constraint">The <see cref="T:System.Data.Constraint" /> to remove.</param>
		/// <exception cref="T:System.ArgumentNullException">The <paramref name="constraint" /> argument is <see langword="null" />.</exception>
		/// <exception cref="T:System.ArgumentException">The constraint does not belong to the collection.</exception>
		// Token: 0x06000A98 RID: 2712 RVA: 0x0002C388 File Offset: 0x0002A588
		public void Remove(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (this.CanRemove(constraint, true))
			{
				this.BaseRemove(constraint);
				this.ArrayRemove(constraint);
				if (constraint is UniqueConstraint && ((UniqueConstraint)constraint).IsPrimaryKey)
				{
					this.Table.PrimaryKey = null;
				}
				this.OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, constraint));
			}
		}

		/// <summary>Removes the <see cref="T:System.Data.Constraint" /> object at the specified index from the collection.</summary>
		/// <param name="index">The index of the <see cref="T:System.Data.Constraint" /> to remove.</param>
		/// <exception cref="T:System.IndexOutOfRangeException">The collection does not have a constraint at this index.</exception>
		// Token: 0x06000A99 RID: 2713 RVA: 0x0002C3EC File Offset: 0x0002A5EC
		public void RemoveAt(int index)
		{
			Constraint constraint = this[index];
			if (constraint == null)
			{
				throw ExceptionBuilder.ConstraintOutOfRange(index);
			}
			this.Remove(constraint);
		}

		/// <summary>Removes the <see cref="T:System.Data.Constraint" /> object specified by name from the collection.</summary>
		/// <param name="name">The name of the <see cref="T:System.Data.Constraint" /> to remove.</param>
		// Token: 0x06000A9A RID: 2714 RVA: 0x0002C414 File Offset: 0x0002A614
		public void Remove(string name)
		{
			Constraint constraint = this[name];
			if (constraint == null)
			{
				throw ExceptionBuilder.ConstraintNotInTheTable(name);
			}
			this.Remove(constraint);
		}

		// Token: 0x06000A9B RID: 2715 RVA: 0x0002C43C File Offset: 0x0002A63C
		internal void UnregisterName(string name)
		{
			if (base.NamesEqual(name, this.MakeName(this._defaultNameIndex - 1), true, this._table.Locale) != 0)
			{
				do
				{
					this._defaultNameIndex--;
				}
				while (this._defaultNameIndex > 1 && !this.Contains(this.MakeName(this._defaultNameIndex - 1)));
			}
		}

		// Token: 0x06000A9C RID: 2716 RVA: 0x0002C49C File Offset: 0x0002A69C
		internal void FinishInitConstraints()
		{
			if (this._delayLoadingConstraints == null)
			{
				return;
			}
			for (int i = 0; i < this._delayLoadingConstraints.Length; i++)
			{
				if (this._delayLoadingConstraints[i] is UniqueConstraint)
				{
					if (!this._fLoadForeignKeyConstraintsOnly)
					{
						UniqueConstraint uniqueConstraint = (UniqueConstraint)this._delayLoadingConstraints[i];
						if (uniqueConstraint._columnNames == null)
						{
							this.Add(uniqueConstraint);
						}
						else
						{
							int num = uniqueConstraint._columnNames.Length;
							DataColumn[] array = new DataColumn[num];
							for (int j = 0; j < num; j++)
							{
								array[j] = this._table.Columns[uniqueConstraint._columnNames[j]];
							}
							if (uniqueConstraint._bPrimaryKey)
							{
								if (this._table._primaryKey != null)
								{
									throw ExceptionBuilder.AddPrimaryKeyConstraint();
								}
								this.Add(uniqueConstraint.ConstraintName, array, true);
							}
							else
							{
								UniqueConstraint constraint = new UniqueConstraint(uniqueConstraint._constraintName, array);
								if (this.FindConstraint(constraint) == null)
								{
									this.Add(constraint);
								}
							}
						}
					}
				}
				else
				{
					ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)this._delayLoadingConstraints[i];
					if (foreignKeyConstraint._parentColumnNames == null || foreignKeyConstraint._childColumnNames == null)
					{
						this.Add(foreignKeyConstraint);
					}
					else if (this._table.DataSet == null)
					{
						this._fLoadForeignKeyConstraintsOnly = true;
					}
					else
					{
						int num = foreignKeyConstraint._parentColumnNames.Length;
						DataColumn[] array = new DataColumn[num];
						DataColumn[] array2 = new DataColumn[num];
						for (int k = 0; k < num; k++)
						{
							if (foreignKeyConstraint._parentTableNamespace == null)
							{
								array[k] = this._table.DataSet.Tables[foreignKeyConstraint._parentTableName].Columns[foreignKeyConstraint._parentColumnNames[k]];
							}
							else
							{
								array[k] = this._table.DataSet.Tables[foreignKeyConstraint._parentTableName, foreignKeyConstraint._parentTableNamespace].Columns[foreignKeyConstraint._parentColumnNames[k]];
							}
							array2[k] = this._table.Columns[foreignKeyConstraint._childColumnNames[k]];
						}
						this.Add(new ForeignKeyConstraint(foreignKeyConstraint._constraintName, array, array2)
						{
							AcceptRejectRule = foreignKeyConstraint._acceptRejectRule,
							DeleteRule = foreignKeyConstraint._deleteRule,
							UpdateRule = foreignKeyConstraint._updateRule
						});
					}
				}
			}
			if (!this._fLoadForeignKeyConstraintsOnly)
			{
				this._delayLoadingConstraints = null;
			}
		}

		// Token: 0x06000A9D RID: 2717 RVA: 0x000108A6 File Offset: 0x0000EAA6
		internal ConstraintCollection()
		{
			ThrowStub.ThrowNotSupportedException();
		}

		// Token: 0x04000782 RID: 1922
		private readonly DataTable _table;

		// Token: 0x04000783 RID: 1923
		private readonly ArrayList _list;

		// Token: 0x04000784 RID: 1924
		private int _defaultNameIndex;

		// Token: 0x04000785 RID: 1925
		private CollectionChangeEventHandler _onCollectionChanged;

		// Token: 0x04000786 RID: 1926
		private Constraint[] _delayLoadingConstraints;

		// Token: 0x04000787 RID: 1927
		private bool _fLoadForeignKeyConstraintsOnly;
	}
}
