using System;

namespace System.Xml.Serialization
{
	/// <summary>Controls the schema generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> when a class instance is serialized as SOAP encoded XML.</summary>
	// Token: 0x020002B7 RID: 695
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Interface)]
	public class SoapTypeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class.</summary>
		// Token: 0x06001A57 RID: 6743 RVA: 0x00098810 File Offset: 0x00096A10
		public SoapTypeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class and specifies the name of the XML type.</summary>
		/// <param name="typeName">The name of the XML type that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates when it serializes the class instance (and recognizes when it deserializes the class instance). </param>
		// Token: 0x06001A58 RID: 6744 RVA: 0x0009881F File Offset: 0x00096A1F
		public SoapTypeAttribute(string typeName)
		{
			this.typeName = typeName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class and specifies the name and XML namespace of the type.</summary>
		/// <param name="typeName">The name of the XML type that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates when it serializes the class instance (and recognizes when it deserializes the class instance). </param>
		/// <param name="ns">The XML namespace of the type. </param>
		// Token: 0x06001A59 RID: 6745 RVA: 0x00098835 File Offset: 0x00096A35
		public SoapTypeAttribute(string typeName, string ns)
		{
			this.typeName = typeName;
			this.ns = ns;
		}

		/// <summary>Gets or sets a value that indicates whether to include the type in SOAP-encoded XML Schema documents.</summary>
		/// <returns>
		///     <see langword="true" /> to include the type in SOAP-encoded XML Schema documents; otherwise, <see langword="false" />. The default is <see langword="true" />.</returns>
		// Token: 0x170004FF RID: 1279
		// (get) Token: 0x06001A5A RID: 6746 RVA: 0x00098852 File Offset: 0x00096A52
		// (set) Token: 0x06001A5B RID: 6747 RVA: 0x0009885A File Offset: 0x00096A5A
		public bool IncludeInSchema
		{
			get
			{
				return this.includeInSchema;
			}
			set
			{
				this.includeInSchema = value;
			}
		}

		/// <summary>Gets or sets the name of the XML type.</summary>
		/// <returns>The name of the XML type. The default is the class name.</returns>
		// Token: 0x17000500 RID: 1280
		// (get) Token: 0x06001A5C RID: 6748 RVA: 0x00098863 File Offset: 0x00096A63
		// (set) Token: 0x06001A5D RID: 6749 RVA: 0x00098879 File Offset: 0x00096A79
		public string TypeName
		{
			get
			{
				if (this.typeName != null)
				{
					return this.typeName;
				}
				return string.Empty;
			}
			set
			{
				this.typeName = value;
			}
		}

		/// <summary>Gets or sets the namespace of the XML type.</summary>
		/// <returns>The namespace of the XML type. The default is an empty string ("").</returns>
		// Token: 0x17000501 RID: 1281
		// (get) Token: 0x06001A5E RID: 6750 RVA: 0x00098882 File Offset: 0x00096A82
		// (set) Token: 0x06001A5F RID: 6751 RVA: 0x0009888A File Offset: 0x00096A8A
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		// Token: 0x04001963 RID: 6499
		private string ns;

		// Token: 0x04001964 RID: 6500
		private string typeName;

		// Token: 0x04001965 RID: 6501
		private bool includeInSchema = true;
	}
}
