using System;

namespace System.Xml.Serialization
{
	/// <summary>Signifies that the code was generated by the serialization infrastructure and can be reused for increased performance, when this attribute is applied to an assembly.</summary>
	// Token: 0x02000307 RID: 775
	[AttributeUsage(AttributeTargets.Assembly)]
	public sealed class XmlSerializerVersionAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class. </summary>
		// Token: 0x06002043 RID: 8259 RVA: 0x000021EA File Offset: 0x000003EA
		public XmlSerializerVersionAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class for the specified type.</summary>
		/// <param name="type">The type that is being serialized.</param>
		// Token: 0x06002044 RID: 8260 RVA: 0x000D0B2C File Offset: 0x000CED2C
		public XmlSerializerVersionAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Gets or sets the identity of the parent assembly.</summary>
		/// <returns>The version of the parent assembly.</returns>
		// Token: 0x1700061C RID: 1564
		// (get) Token: 0x06002045 RID: 8261 RVA: 0x000D0B3B File Offset: 0x000CED3B
		// (set) Token: 0x06002046 RID: 8262 RVA: 0x000D0B43 File Offset: 0x000CED43
		public string ParentAssemblyId
		{
			get
			{
				return this.mvid;
			}
			set
			{
				this.mvid = value;
			}
		}

		/// <summary>Gets or sets the assembly's version number.</summary>
		/// <returns>The version of the assembly.</returns>
		// Token: 0x1700061D RID: 1565
		// (get) Token: 0x06002047 RID: 8263 RVA: 0x000D0B4C File Offset: 0x000CED4C
		// (set) Token: 0x06002048 RID: 8264 RVA: 0x000D0B54 File Offset: 0x000CED54
		public string Version
		{
			get
			{
				return this.serializerVersion;
			}
			set
			{
				this.serializerVersion = value;
			}
		}

		/// <summary>Gets or sets the common language runtime (CLR) namespace of the assembly.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the common language runtime (CLR) namespace of the assembly.</returns>
		// Token: 0x1700061E RID: 1566
		// (get) Token: 0x06002049 RID: 8265 RVA: 0x000D0B5D File Offset: 0x000CED5D
		// (set) Token: 0x0600204A RID: 8266 RVA: 0x000D0B65 File Offset: 0x000CED65
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the type that the serializer operates on.</summary>
		/// <returns>The <see cref="T:System.Type" /> to be serialized.</returns>
		// Token: 0x1700061F RID: 1567
		// (get) Token: 0x0600204B RID: 8267 RVA: 0x000D0B6E File Offset: 0x000CED6E
		// (set) Token: 0x0600204C RID: 8268 RVA: 0x000D0B76 File Offset: 0x000CED76
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		// Token: 0x04001B21 RID: 6945
		private string mvid;

		// Token: 0x04001B22 RID: 6946
		private string serializerVersion;

		// Token: 0x04001B23 RID: 6947
		private string ns;

		// Token: 0x04001B24 RID: 6948
		private Type type;
	}
}
