using System;

namespace System.Xml.Serialization
{
	/// <summary>Indicates to the <see cref="T:System.Xml.Serialization.XmlSerializer" /> that the member must be treated as XML text when the class that contains it is serialized or deserialized.</summary>
	// Token: 0x02000308 RID: 776
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlTextAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlTextAttribute" /> class.</summary>
		// Token: 0x0600204D RID: 8269 RVA: 0x000021EA File Offset: 0x000003EA
		public XmlTextAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlTextAttribute" /> class.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> of the member to be serialized. </param>
		// Token: 0x0600204E RID: 8270 RVA: 0x000D0B7F File Offset: 0x000CED7F
		public XmlTextAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Gets or sets the type of the member.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x17000620 RID: 1568
		// (get) Token: 0x0600204F RID: 8271 RVA: 0x000D0B8E File Offset: 0x000CED8E
		// (set) Token: 0x06002050 RID: 8272 RVA: 0x000D0B96 File Offset: 0x000CED96
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition language (XSD) data type of the text generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema (XSD) data type, as defined by the World Wide Web Consortium (www.w3.org) document "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the .NET data type. </exception>
		/// <exception cref="T:System.InvalidOperationException">The XML Schema data type you have specified is invalid for the property and cannot be converted to the member type. </exception>
		// Token: 0x17000621 RID: 1569
		// (get) Token: 0x06002051 RID: 8273 RVA: 0x000D0B9F File Offset: 0x000CED9F
		// (set) Token: 0x06002052 RID: 8274 RVA: 0x000D0BB5 File Offset: 0x000CEDB5
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		// Token: 0x04001B25 RID: 6949
		private Type type;

		// Token: 0x04001B26 RID: 6950
		private string dataType;
	}
}
