using System;

namespace System.Data.SqlClient
{
	/// <summary>Represents the set of arguments passed to the notification event handler.</summary>
	// Token: 0x02000212 RID: 530
	public class SqlNotificationEventArgs : EventArgs
	{
		/// <summary>Creates a new instance of the <see cref="T:System.Data.SqlClient.SqlNotificationEventArgs" /> object.</summary>
		/// <param name="type">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationType" /> value that indicates whether this notification is generated because of an actual change, or by the subscription.</param>
		/// <param name="info">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationInfo" /> value that indicates the reason for the notification event. This may occur because the data in the store actually changed, or the notification became invalid (for example, it timed out).</param>
		/// <param name="source">
		///   <see cref="T:System.Data.SqlClient.SqlNotificationSource" /> value that indicates the source that generated the notification.</param>
		// Token: 0x060019BB RID: 6587 RVA: 0x000772B9 File Offset: 0x000754B9
		public SqlNotificationEventArgs(SqlNotificationType type, SqlNotificationInfo info, SqlNotificationSource source)
		{
			this._info = info;
			this._source = source;
			this._type = type;
		}

		/// <summary>Gets a value that indicates whether this notification is generated because of an actual change, or by the subscription.</summary>
		/// <returns>A value indicating whether the notification was generated by a change or a subscription.</returns>
		// Token: 0x170004C7 RID: 1223
		// (get) Token: 0x060019BC RID: 6588 RVA: 0x000772D6 File Offset: 0x000754D6
		public SqlNotificationType Type
		{
			get
			{
				return this._type;
			}
		}

		/// <summary>Gets a value that indicates the reason for the notification event, such as a row in the database being modified or a table being truncated.</summary>
		/// <returns>The notification event reason.</returns>
		// Token: 0x170004C8 RID: 1224
		// (get) Token: 0x060019BD RID: 6589 RVA: 0x000772DE File Offset: 0x000754DE
		public SqlNotificationInfo Info
		{
			get
			{
				return this._info;
			}
		}

		/// <summary>Gets a value that indicates the source that generated the notification, such as a change to the query data or the database's state.</summary>
		/// <returns>The source of the notification.</returns>
		// Token: 0x170004C9 RID: 1225
		// (get) Token: 0x060019BE RID: 6590 RVA: 0x000772E6 File Offset: 0x000754E6
		public SqlNotificationSource Source
		{
			get
			{
				return this._source;
			}
		}

		// Token: 0x060019BF RID: 6591 RVA: 0x000772EE File Offset: 0x000754EE
		// Note: this type is marked as 'beforefieldinit'.
		static SqlNotificationEventArgs()
		{
		}

		// Token: 0x040010A6 RID: 4262
		private SqlNotificationType _type;

		// Token: 0x040010A7 RID: 4263
		private SqlNotificationInfo _info;

		// Token: 0x040010A8 RID: 4264
		private SqlNotificationSource _source;

		// Token: 0x040010A9 RID: 4265
		internal static SqlNotificationEventArgs s_notifyError = new SqlNotificationEventArgs(SqlNotificationType.Subscribe, SqlNotificationInfo.Error, SqlNotificationSource.Object);
	}
}
