using System;
using System.CodeDom;
using System.Collections.Specialized;
using System.Xml.Schema;

namespace System.Xml.Serialization.Advanced
{
	// Token: 0x02000322 RID: 802
	internal class MappedTypeDesc
	{
		// Token: 0x06002103 RID: 8451 RVA: 0x000D2280 File Offset: 0x000D0480
		internal MappedTypeDesc(string clrType, string name, string ns, XmlSchemaType xsdType, XmlSchemaObject context, SchemaImporterExtension extension, CodeNamespace code, StringCollection references)
		{
			this.clrType = clrType.Replace('+', '.');
			this.name = name;
			this.ns = ns;
			this.xsdType = xsdType;
			this.context = context;
			this.code = code;
			this.references = references;
			this.extension = extension;
		}

		// Token: 0x17000658 RID: 1624
		// (get) Token: 0x06002104 RID: 8452 RVA: 0x000D22D9 File Offset: 0x000D04D9
		internal SchemaImporterExtension Extension
		{
			get
			{
				return this.extension;
			}
		}

		// Token: 0x17000659 RID: 1625
		// (get) Token: 0x06002105 RID: 8453 RVA: 0x000D22E1 File Offset: 0x000D04E1
		internal string Name
		{
			get
			{
				return this.clrType;
			}
		}

		// Token: 0x1700065A RID: 1626
		// (get) Token: 0x06002106 RID: 8454 RVA: 0x000D22E9 File Offset: 0x000D04E9
		internal StringCollection ReferencedAssemblies
		{
			get
			{
				if (this.references == null)
				{
					this.references = new StringCollection();
				}
				return this.references;
			}
		}

		// Token: 0x06002107 RID: 8455 RVA: 0x000D2304 File Offset: 0x000D0504
		internal CodeTypeDeclaration ExportTypeDefinition(CodeNamespace codeNamespace, CodeCompileUnit codeCompileUnit)
		{
			if (this.exported)
			{
				return null;
			}
			this.exported = true;
			foreach (object obj in this.code.Imports)
			{
				CodeNamespaceImport value = (CodeNamespaceImport)obj;
				codeNamespace.Imports.Add(value);
			}
			CodeTypeDeclaration codeTypeDeclaration = null;
			string @string = Res.GetString("This type definition was generated by {0} schema importer extension.", new object[]
			{
				this.extension.GetType().FullName
			});
			foreach (object obj2 in this.code.Types)
			{
				CodeTypeDeclaration codeTypeDeclaration2 = (CodeTypeDeclaration)obj2;
				if (this.clrType == codeTypeDeclaration2.Name)
				{
					if (codeTypeDeclaration != null)
					{
						throw new InvalidOperationException(Res.GetString("Schema importer extension {0} generated duplicate type definitions: {1}.", new object[]
						{
							this.extension.GetType().FullName,
							this.clrType
						}));
					}
					codeTypeDeclaration = codeTypeDeclaration2;
				}
				codeTypeDeclaration2.Comments.Add(new CodeCommentStatement(@string, false));
				codeNamespace.Types.Add(codeTypeDeclaration2);
			}
			if (codeCompileUnit != null)
			{
				foreach (string value2 in this.ReferencedAssemblies)
				{
					if (!codeCompileUnit.ReferencedAssemblies.Contains(value2))
					{
						codeCompileUnit.ReferencedAssemblies.Add(value2);
					}
				}
			}
			return codeTypeDeclaration;
		}

		// Token: 0x04001B76 RID: 7030
		private string name;

		// Token: 0x04001B77 RID: 7031
		private string ns;

		// Token: 0x04001B78 RID: 7032
		private XmlSchemaType xsdType;

		// Token: 0x04001B79 RID: 7033
		private XmlSchemaObject context;

		// Token: 0x04001B7A RID: 7034
		private string clrType;

		// Token: 0x04001B7B RID: 7035
		private SchemaImporterExtension extension;

		// Token: 0x04001B7C RID: 7036
		private CodeNamespace code;

		// Token: 0x04001B7D RID: 7037
		private bool exported;

		// Token: 0x04001B7E RID: 7038
		private StringCollection references;
	}
}
